  
language: bash

sudo: required
services:
  - docker

before_install:
 - docker system prune -a -f

script:
jobs:
  include:
    - stage: test
      language: csharp
      dotnet: 3.1
      mono: none
      script:
      - dotnet restore AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
      - dotnet build AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
      - dotnet test AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
    - stage: build pack publish
      services:
        - docker
      script: 
      - docker build -t softek-demo .
      - docker images
      - docker tag softek-demo $DOCKER_USER/softek-demo
      after_success:
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - docker push $DOCKER_USER/softek-demo
    - stage: test image
      script:
      - docker images
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - docker run -d $DOCKER_USER/softek-demo
      - docker ps
      - docker stop $(docker ps -a -q)
      - docker ps

