  
language: bash

sudo: required
services:
  - docker

before_install:
 - docker system prune -a -f
 
env:
  global:
    - DOCKER_IMAGE=softek-demo
    - DOCKER_ENGINE_VERSION=17.06.0
    - DOCKER_COMPOSE_VERSION=3.3
    - REDIS_CONNECTIONSTRING=localhost:5001
    
script:
jobs:
  include:
    - stage: test image
      script:
      - docker images
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - docker network create -d bridge softek-network
      - docker run --name redis -d -p 5001:6379 --network softek-network redis
      - docker ps
      - docker run -d -p 5000:80 --network softek-network --name asp-web --link redis $DOCKER_USER/$DOCKER_IMAGE
      - docker ps
      - curl -d "@data.json" -X POST http://localhost:5000/weatherforecast
      - curl http://localhost:5000/weatherforecas
      - docker stop $(docker ps -a -q)
      - docker ps
      

