  
language: bash

sudo: required
services:
  - docker

before_install:
 - docker system prune -a -f
 
env:
  global:
    - DOCKER_IMAGE=softek-demo
    - DOCKER_ENGINE_VERSION=17.06.0
    - DOCKER_COMPOSE_VERSION=3.3
    - REDIS_CONNECTIONSTRING=localhost:6379
    - ASPNETCORE_URLS=http://+:5000
    
script:
jobs:
  include:
    - stage: run docker-compose
      script:
      - docker-compose up -d -p 5000:5000
      # Verify service availability
      - docker-compose ps
      - curl http://localhost:5000/weatherforecas
      after_success:
      - docker-compose down
    
      

