  
language: bash

sudo: required
services:
  - docker

before_install:
 - docker system prune -a -f

script:
jobs:
  include:
    - stage: test
      language: csharp
      dotnet: 3.1
      mono: none
      script:
      - dotnet restore AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
      - dotnet build AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
      - dotnet test AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
    - stage: build pack publish
      services:
        - docker
      script: 
      - docker build -t softek-demo .
      - docker images
      - docker tag softek-demo pcheremu/softek-demo
      #- docker push $DOCKER_USERNAME/softek-demo
    - stage: test image
      script: 
      - docker run -d softek-demo:latest
      - docker ps
      - docker stop softek-demo
      - docker ps
    #- script: docker run softek-demo
