  
language: bash

sudo: required
services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=3.9
    - COMPOSE_FILES="docker-compose.yml"

before_install:
 - docker system prune -a -f

script:
jobs:
  include:
    - stage: test
      language: csharp
      dotnet: 3.1
      mono: none
      script:
      - dotnet restore AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
      - dotnet build AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
      - dotnet test AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
    - stage: build pack publish
      services:
        - docker
      script: 
      - docker build --no-cache -t softek-demo .
      - docker images
      #- docker-compose ${COMPOSE_FILES} build --no-cache
      #- docker-compose up -d
      - docker tag softek-demo pcheremu/softek-demo
      #- docker push $DOCKER_USERNAME/softek-demo
    #- stage: test image
    #  script: 
    #  - docker run softek-demo
    #- script: docker run softek-demo
