language: csharp
mono: none
dist: bionic
dotnet: 3.1
install:
  - dotnet restore AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
script:
  - dotnet build AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
  - dotnet test AS.Redis.Connector.Test/AS.Redis.Connector.Test.csproj
