version: "3.3"
services:
  # First the AspNet Core app
  web:
    ## Get the image to use and set the container name
    image: softektask:latest
    container_name: softektask

    # State a dependancy on Redis working
    depends_on:
      - "redis"

    # Location of the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    # Set access ports for localhost on the left
    ports:
      - "5000:80"
    # Configure a link to Redis
    links:
      - "redis"

    # The Application needs a connection string for Redis, this just needs to be the Redis Service name as defined below
    # Pass it in as an Environmental Variable
    environment:
      - RedisConnection=redis
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      #- REDIS_CONNECTIONSTRING=localhost:6379

  # The Redis Service, this label is required for the "Links" and Connection string
  redis:
    # Pull the image from Docker Hub
    image: redis

    # Give the container a name (any name you want)
    container_name: Redis
    ports:
      - "6379:6379"
